# Generated by Django 4.2.1 on 2023-05-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_categories_post_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
