# Generated by Django 4.2.1 on 2023-05-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
