# Generated by Django 4.2.1 on 2023-06-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default={'cols': 80, 'rows': 30}),
        ),
    ]
